name: Auto Update Proxies

on:
  schedule:
    - cron: '0 0,12 * * *'  # Run at 00:00 and 12:00 UTC every day

jobs:
  update-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: main  # Checkout the main branch where update_proxies.py resides

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aiohttp

      - name: Run script to update proxies
        run: python update_proxies.py > updated_proxies.txt

      - name: Update README
        run: |
          echo "## Updated Proxies" > README.md
          echo "Last updated: $(date)" >> README.md
          echo "" >> README.md
          awk -F '\t' 'BEGIN {print "| IP Address | Port | Type | Protocol | Anonymity |"} {print "| "$1" | "$2" | "$3" | "$4" | "$5" " |"}' updated_proxies.txt >> README.md

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Pull latest changes
        run: git pull origin main

      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "Update proxies $(date)" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Verify push
        run: git log -1
